use crate::ast_visitor::ModelInfo;
use std::collections::HashSet;

/// `ModelInfo` から Burn の Rust コードを生成する
pub fn generate(models: &[ModelInfo]) -> String {
    let mut out = String::new();
    let mut imports = collect_imports(models);

    // ── ヘッダコメント ────────────────────────────────────────────────────
    out.push_str("// Auto-generated by py_parser (PyTorch → Burn converter)\n");
    out.push_str("// Review and adjust generic dimension parameters as needed.\n\n");

    // ── use 宣言 ────────────────────────────────────────────────────────
    imports.sort();
    for imp in &imports {
        out.push_str(&format!("use {};\n", imp));
    }
    out.push('\n');

    for model in models {
        out.push_str(&generate_model(model));
        out.push('\n');
    }
    out
}

fn collect_imports(models: &[ModelInfo]) -> Vec<String> {
    let mut set: HashSet<String> = HashSet::new();
    set.insert("burn::prelude::*".to_string());
    set.insert("burn::nn::*".to_string());

    for model in models {
        for field in &model.fields {
            let imp = field.layer_info.burn_import;
            if !imp.is_empty() {
                set.insert(imp.to_string());
            }
        }
    }
    set.into_iter().collect()
}

fn generate_model(model: &ModelInfo) -> String {
    let name = &model.class_name;
    let mut out = String::new();

    // ── struct ────────────────────────────────────────────────────────────
    out.push_str("#[derive(Module, Debug)]\n");
    out.push_str(&format!("pub struct {}<B: Backend> {{\n", name));
    for field in &model.fields {
        let ty = if field.layer_info.needs_backend {
            format!("{}<B>", field.layer_info.burn_type)
        } else {
            field.layer_info.burn_type.to_string()
        };
        out.push_str(&format!("    pub {}: {},\n", field.name, ty));
    }
    out.push_str("}\n\n");

    // ── impl ──────────────────────────────────────────────────────────────
    out.push_str(&format!("impl<B: Backend> {}<B> {{\n", name));

    // ── new() ──────────────────────────────────────────────────────────────
    out.push_str("    pub fn new(device: &B::Device) -> Self {\n");
    out.push_str("        Self {\n");
    for field in &model.fields {
        out.push_str(&format!(
            "            {}: {},\n",
            field.name, field.init_expr
        ));
    }
    out.push_str("        }\n");
    out.push_str("    }\n\n");

    // ── forward() ─────────────────────────────────────────────────────────
    let forward_args = if model.forward_args.is_empty() {
        "x: Tensor<B, 2>".to_string()
    } else {
        model
            .forward_args
            .iter()
            .enumerate()
            .map(|(i, arg)| {
                // 推測: 最初の引数は Tensor<B, 2>、追加は任意
                if i == 0 {
                    format!("{}: Tensor<B, 2>", arg)
                } else {
                    format!("{}: Tensor<B, 2>", arg)
                }
            })
            .collect::<Vec<_>>()
            .join(", ")
    };

    out.push_str(&format!(
        "    pub fn forward(&self, {}) -> Tensor<B, 2> {{\n",
        forward_args
    ));

    for stmt in &model.forward_stmts {
        out.push_str(&format!("        {}\n", stmt));
    }

    if let Some(ret) = &model.return_expr {
        out.push_str(&format!("        {}\n", ret));
    } else if !model.forward_stmts.is_empty() {
        // 最後の let 文の変数名を戻り値とする
        if let Some(last) = model.forward_stmts.last() {
            if let Some(var) = extract_let_var(last) {
                out.push_str(&format!("        {}\n", var));
            }
        }
    }

    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

/// "let foo = ...;" から "foo" を取り出す
fn extract_let_var(stmt: &str) -> Option<&str> {
    let rest = stmt.strip_prefix("let ")?;
    let end = rest.find([' ', ':'])?;
    Some(&rest[..end])
}
